spring:
  jersey:
    type: filter
    fitler:
      order: 1

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: acmeair-webapp
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
